tapas/config/routes.rb
Tapas::Application.routes.draw do
 root "recipes#index"

  get '/ingredients/new', controller: 'ingredients', action: 'new', as: 'new_ingredient'
  post '/ingredients', controller: 'ingredients', action: 'create', as: 'ingredients'

  get '/ingredients', controller: 'ingredients', action: 'index'
  get '/ingredients/:id', controller: 'ingredients', action: 'show', as: 'ingredient'

  get '/ingredients/:id/edit', controller: 'ingredients', action: 'edit', as: 'edit_ingredient'
  patch '/ingredients/:id', controller: 'ingredients', action: 'update'

  delete '/ingredients/:id', controller: 'ingredients', action: 'destroy'

  get '/recipe_ingredients/new', controller: 'recipe_ingredients', action: 'new', as: 'new_recipe_ingredient'
  post '/recipe_ingredients', controller: 'recipe_ingredients', action: 'create', as: 'recipe_ingredients'

  get '/recipe_ingredients', controller: 'recipe_ingredients', action: 'index'
  get '/recipe_ingredients/:id', controller: 'recipe_ingredients', action: 'show', as: 'recipe_ingredient'

  get '/recipe_ingredients/:id/edit', controller: 'recipe_ingredients', action: 'edit', as: 'edit_recipe_ingredient'
  patch '/recipe_ingredients/:id', controller: 'recipe_ingredients', action: 'update'

  delete '/recipe_ingredients/:id', controller: 'recipe_ingredients', action: 'destroy'

  get '/recipes/new', controller: 'recipes', action: 'new', as: 'new_recipe'
  post '/recipes', controller: 'recipes', action: 'create', as: 'recipes'

  get '/recipes', controller: 'recipes', action: 'index'
  get '/recipes/:id', controller: 'recipes', action: 'show', as: 'recipe'

  get '/recipes/:id/edit', controller: 'recipes', action: 'edit', as: 'edit_recipe'
  patch '/recipes/:id', controller: 'recipes', action: 'update'

  delete '/recipes/:id', controller: 'recipes', action: 'destroy'

end

tapas/app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
end

tapas/app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

tapas/app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
end

tapas/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

tapas/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find_by(id: params[:id])
  end

  def new
  end

  def create
    @ingredient = Ingredient.new
    @ingredient.name = params[:name]
    @ingredient.source = params[:source]
    @ingredient.notes = params[:notes]

    if @ingredient.save
      redirect_to ingredients_url, notice: "Ingredient created successfully."
    else
      render 'new'
    end
  end

  def edit
    @ingredient = Ingredient.find_by(id: params[:id])
  end

  def update
    @ingredient = Ingredient.find_by(id: params[:id])
    @ingredient.name = params[:name]
    @ingredient.source = params[:source]
    @ingredient.notes = params[:notes]

    if @ingredient.save
      redirect_to ingredients_url, notice: "Ingredient updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @ingredient = Ingredient.find_by(id: params[:id])
    @ingredient.destroy

    redirect_to ingredients_url, notice: "Ingredient deleted."
  end
end

tapas/app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController

  def index
    @recipe_ingredients = RecipeIngredient.all
  end

  def show
    @recipe_ingredient = RecipeIngredient.find_by(id: params[:id])
  end

  def new
  end

  def create
    @recipe_ingredient = RecipeIngredient.new
    @recipe_ingredient.recipe_id = params[:recipe_id]
    @recipe_ingredient.ingredient_id = params[:ingredient_id]
    @recipe_ingredient.amount = params[:amount]
    @recipe_ingredient.notes = params[:notes]

    if @recipe_ingredient.save
      redirect_to recipe_ingredients_url, notice: "Recipe ingredient created successfully."
    else
      render 'new'
    end
  end

  def edit
    @recipe_ingredient = RecipeIngredient.find_by(id: params[:id])
  end

  def update
    @recipe_ingredient = RecipeIngredient.find_by(id: params[:id])
    @recipe_ingredient.recipe_id = params[:recipe_id]
    @recipe_ingredient.ingredient_id = params[:ingredient_id]
    @recipe_ingredient.amount = params[:amount]
    @recipe_ingredient.notes = params[:notes]

    if @recipe_ingredient.save
      redirect_to recipe_ingredients_url, notice: "Recipe ingredient updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @recipe_ingredient = RecipeIngredient.find_by(id: params[:id])
    @recipe_ingredient.destroy

    redirect_to recipe_ingredients_url, notice: "Recipe ingredient deleted."
  end
end

tapas/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find_by(id: params[:id])
  end

  def new
  end

  def create
    @recipe = Recipe.new
    @recipe.name = params[:name]
    @recipe.category = params[:category]
    @recipe.quantity = params[:quantity]
    @recipe.calories = params[:calories]
    @recipe.preparation = params[:preparation]
    @recipe.prep_time = params[:prep_time]

    if @recipe.save
      redirect_to recipes_url, notice: "Recipe created successfully."
    else
      render 'new'
    end
  end

  def edit
    @recipe = Recipe.find_by(id: params[:id])
  end

  def update
    @recipe = Recipe.find_by(id: params[:id])
    @recipe.name = params[:name]
    @recipe.category = params[:category]
    @recipe.quantity = params[:quantity]
    @recipe.calories = params[:calories]
    @recipe.preparation = params[:preparation]
    @recipe.prep_time = params[:prep_time]

    if @recipe.save
      redirect_to recipes_url, notice: "Recipe updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find_by(id: params[:id])
    @recipe.destroy

    redirect_to recipes_url, notice: "Recipe deleted."
  end
end

tapas/app/helpers/application_helper.rb
module ApplicationHelper
end

tapas/app/views/ingredients/edit.html.erb
<div class="page-header">
  <h1>Editing Ingredient #<%= @ingredient.id %></h1>
</div>

<%= form_tag(ingredient_url(@ingredient), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :name, @ingredient.name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :source, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :source, @ingredient.source, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :notes, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :notes, @ingredient.notes, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Ingredient", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

tapas/app/views/ingredients/index.html.erb
<div class="page-header">
  <h1>Ingredients</h1>
</div>

<p><%= link_to 'Add a New Ingredient', new_ingredient_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Source</th>
      <th>Notes</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.source %></td>
        <td><%= ingredient.notes %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, ingredient_url(ingredient), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_ingredient_url(ingredient), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, ingredient_url(ingredient), method: 'delete', data: { confirm: "Do you really want to delete this ingredient?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

tapas/app/views/ingredients/new.html.erb
<div class="page-header">
  <h1>New Ingredient</h1>
</div>

<%= form_tag(ingredients_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :name, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :source, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :source, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :notes, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :notes, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Ingredient", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

tapas/app/views/ingredients/show.html.erb
<div class="page-header">
  <h1>Ingredient #<%= @ingredient.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Name</dt>
  <dd><%= @ingredient.name %></dd>

  <dt>Source</dt>
  <dd><%= @ingredient.source %></dd>

  <dt>Notes</dt>
  <dd><%= @ingredient.notes %></dd>

</dl>

tapas/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Tapas</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/amelia/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Recipes", recipes_url %></li>
        <li><%= link_to "Recipe Ingredients", recipe_ingredients_url %></li>
        <li><%= link_to "Ingredients", ingredients_url %></li>
        <li><a href="#">About</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

tapas/app/views/recipe_ingredients/edit.html.erb
<div class="page-header">
  <h1>Editing Recipe Ingredient #<%= @recipe_ingredient.id %></h1>
</div>

<%= form_tag(recipe_ingredient_url(@recipe_ingredient), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :recipe_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :recipe_id, @recipe_ingredient.recipe_id, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :ingredient_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :ingredient_id, @recipe_ingredient.ingredient_id, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :amount, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :amount, @recipe_ingredient.amount, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :notes, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_area_tag :notes, @recipe_ingredient.notes, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Recipe Ingredient", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

tapas/app/views/recipe_ingredients/index.html.erb
<div class="page-header">
  <h1>Recipe ingredients</h1>
</div>

<p><%= link_to 'Add a New Recipe Ingredient', new_recipe_ingredient_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Recipe</th>
      <th>Ingredient</th>
      <th>Amount</th>
      <th>Notes</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recipe_ingredients.each do |recipe_ingredient| %>
      <tr>
        <td><%= recipe_ingredient.recipe_id %></td>
        <td><%= recipe_ingredient.ingredient_id %></td>
        <td><%= recipe_ingredient.amount %></td>
        <td><%= recipe_ingredient.notes %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, recipe_ingredient_url(recipe_ingredient), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_recipe_ingredient_url(recipe_ingredient), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, recipe_ingredient_url(recipe_ingredient), method: 'delete', data: { confirm: "Do you really want to delete this recipe_ingredient?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

tapas/app/views/recipe_ingredients/new.html.erb
<div class="page-header">
  <h1>New Recipe Ingredient</h1>
</div>

<%= form_tag(recipe_ingredients_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :recipe_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :recipe_id, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :ingredient_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :ingredient_id, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :amount, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :amount, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :notes, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_area_tag :notes, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Recipe Ingredient", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

tapas/app/views/recipe_ingredients/show.html.erb
<div class="page-header">
  <h1>Recipe Ingredient #<%= @recipe_ingredient.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Recipe</dt>
  <dd><%= @recipe_ingredient.recipe_id %></dd>

  <dt>Ingredient</dt>
  <dd><%= @recipe_ingredient.ingredient_id %></dd>

  <dt>Amount</dt>
  <dd><%= @recipe_ingredient.amount %></dd>

  <dt>Notes</dt>
  <dd><%= @recipe_ingredient.notes %></dd>

</dl>

tapas/app/views/recipes/edit.html.erb
<div class="page-header">
  <h1>Editing Recipe #<%= @recipe.id %></h1>
</div>

<%= form_tag(recipe_url(@recipe), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :name, @recipe.name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :image, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :image, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :category, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :category, @recipe.category, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :quantity, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :quantity, @recipe.quantity, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :calories, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :calories, @recipe.calories, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :preparation, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :preparation, @recipe.preparation, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :prep_time, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_area_tag :prep_time, @recipe.prep_time, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Recipe", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

tapas/app/views/recipes/index.html.erb
<div class="page-header">
  <h1>Recipes</h1>
</div>

<p><%= link_to 'Add a New Recipe', new_recipe_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Category</th>
      <th>Quantity</th>
      <th>Calories</th>
      <th>Preparation</th>
      <th>Prep time</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= image_tag recipe.image, width:100 %></td>
        <td><%= recipe.category %></td>
        <td><%= recipe.quantity %></td>
        <td><%= recipe.calories %></td>
        <td><%= recipe.preparation %></td>
        <td><%= recipe.prep_time %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, recipe_url(recipe), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_recipe_url(recipe), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, recipe_url(recipe), method: 'delete', data: { confirm: "Do you really want to delete this recipe?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

tapas/app/views/recipes/new.html.erb
<div class="page-header">
  <h1>New Recipe</h1>
</div>

<%= form_tag(recipes_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :name, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :image, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :image, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :category, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :category, nil, class: 'form-control' %>
    </div>
  </div>


  <div class="form-group">
    <%= label_tag :quantity, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :quantity, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :calories, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :calories, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :preparation, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :preparation, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :prep_time, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_area_tag :prep_time, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Recipe", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

tapas/app/views/recipes/show.html.erb
<div class="page-header">
  <h1>Recipe #<%= @recipe.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Name</dt>
  <dd><%= @recipe.name %></dd>

  <dt>Category</dt>
  <dd><%= @recipe.category %></dd>

  <dt>Quantity</dt>
  <dd><%= @recipe.quantity %></dd>

  <dt>Calories</dt>
  <dd><%= @recipe.calories %></dd>

  <dt>Preparation</dt>
  <dd><%= @recipe.preparation %></dd>

  <dt>Prep time</dt>
  <dd><%= @recipe.prep_time %></dd>

</dl>